-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'EXERCISE_REVIEW_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE 'EXERCISE_PR_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'EXERCISE_CHALLENGE_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'EXERCISE_CHANGES_REQUESTED';
