import "~/styles/globals.css";

import { auth } from '@clerk/nextjs/server';
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Code Wise",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  auth().protect({
    unauthenticatedUrl: '/login'
  })

  return (
    <>
      {children}
    </>
  );
}
