ALTER TYPE "MentorshipActionStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMEDIATION_ACTION_DUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REMEDIATION_ACTION_OVERDUE';
